ON-10 connexion db
CDjepeno/OnlineBookApi pull request #12
Opened 2023-08-01 16:01 UTC by hassanrobleh

2023-08-01 20:43 UTC, CDjepeno requested changes

2023-08-01 20:43 UTC, CDjepeno commented on src/infra/nest/src/app.module.ts
>    controllers: [AppController],
Ligne 27-36 j'ai des commentaires essaie de les supprimer stp

2023-08-01 21:27 UTC, hassanrobleh commented on src/infra/nest/src/app.module.ts
>    controllers: [AppController],
j'ai checké le fichier app.module mais Je ne vois pas du tout des commentaires sur la  ligne 27-36.

2023-08-02 10:06 UTC, Chris-wemanity commented on src/infra/nest/src/app.module.ts
>    controllers: [AppController],
ok je merge alors pas de souci 🚀

2023-08-02 10:09 UTC, CDjepeno commented on src/infra/nest/src/app.module.ts
>    controllers: [AppController],
Ok je merge alors :rocket:

2023-08-02 10:09 UTC, CDjepeno approved these changes

2023-08-02 10:11 UTC, merged