ON-15 Refactorisation projet Nestjs
CDjepeno/OnlineBookApi pull request #15
Opened 2023-08-08 09:45 UTC by hassanrobleh

2023-08-08 13:50 UTC, Chris-wemanity requested changes

2023-08-08 13:50 UTC, Chris-wemanity commented on src/infra/nest/src/core/repository/userRepository.ts
> +export const IUserRepository = Symbol('IUserRepository');
Pourquoi t'a mis cette ligne ?

2023-08-08 13:50 UTC, Chris-wemanity commented on src/infra/nest/src/core/application/useCases/createUser/createUser.ts
> +      console.log(user);
Enlever le console.log

2023-08-08 13:50 UTC, Chris-wemanity commented on src/infra/nest/src/users/users.controller.ts
> +    return this.userService.createUser(userDto);
Il faut utiliser ton use case 'createUser' par injection de dépendance ici

2023-08-08 14:33 UTC, hassanrobleh commented on src/infra/nest/src/core/application/useCases/createUser/createUser.ts
> +      console.log(user);
ok

2023-08-08 14:34 UTC, hassanrobleh commented on src/infra/nest/src/users/users.controller.ts
> +    return this.userService.createUser(userDto);
J'avais du mal à l'utiliser

2023-08-08 18:55 UTC, Chris-wemanity commented on src/infra/nest/src/core/application/useCases/createUser/createUser.ts
Il faut mettre ce fichier dans un dossier user

2023-09-08 23:09 UTC, CDjepeno approved these changes

2023-09-08 23:09 UTC, merged