On 25 faire les tests unitaires pour le uscase register
CDjepeno/OnlineBookApi pull request #20
Opened 2023-09-29 16:36 UTC by hassanrobleh

2023-10-04 13:26 UTC, CDjepeno requested changes

2023-10-04 13:26 UTC, CDjepeno commented on src/infra/nest/src/test/unitaire/use.case/user/user.fixture.ts
> +            throw new Error(err)
Tu n'a pas besoin d'envolopper dans un un BookError => throw err suffi

2023-10-04 13:26 UTC, CDjepeno commented on src/infra/nest/src/test/unitaire/use.case/user/create.user.spec.ts
> +      expect(err.message).toBe("Error: Numero n'est pas valide");
Du coup tu n'es plus obligé de mentionner: "Error:"

2023-10-04 13:26 UTC, CDjepeno commented on src/infra/nest/src/infras/controllers/user/users.controller.ts
> +      throw new BookError(err)
Pareil ici tu n'es pas obligé d'envelopper l'erreur

2023-10-08 19:28 UTC, CDjepeno requested changes

2023-10-08 19:28 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/create.user.usecase.ts
> +        throw new Error("Numero n'est pas valide");
Il s'agit d'une erreur métier, il ne fallait pas enlever la classe BookError.
Et il faudra revoir le nom de cette classe "BookError" => "InvalidPhoneNumberException"

2023-10-08 19:35 UTC, CDjepeno requested changes

2023-10-08 19:35 UTC, CDjepeno commented on src/infra/nest/src/test/unitaire/data/mock/mock.user.provider.ts
Cette classe j'ai l'impression que tu ne l'utilise pas dans le projet, il faut donc la supprimer stp

2023-10-10 07:59 UTC, CDjepeno requested changes

2023-10-10 07:59 UTC, CDjepeno commented on src/infra/nest/src/test/unitaire/use.case/user/create.user.spec.ts
> +      expect(err.message).toBe("Numero n'est pas valisde");
ta fait une faute de frappe ici "valisde"

2023-10-10 07:59 UTC, CDjepeno commented on src/infra/nest/src/domaine/errors/book.error.ts
> +export class BookError extends Error {}
ta pas oublier d'implementer ici ?

2023-10-10 08:07 UTC, hassanrobleh commented on src/infra/nest/src/domaine/errors/book.error.ts
> +export class BookError extends Error {}
tu veux dire implementer la methode InvalidPhoneNumberException()

2023-10-10 10:07 UTC, CDjepeno commented on src/infra/nest/src/domaine/errors/book.error.ts
> +export class BookError extends Error {}
Oui voila la classe plutôt InvalidPhoneNumberException

2023-10-15 10:07 UTC, CDjepeno requested changes

2023-10-15 10:07 UTC, CDjepeno commented on src/infra/nest/src/domaine/errors/book.error.ts
> +    statusCode?: number = 400;
Le point d'interrogation, tu l'a mis pourquoi ?
Il est pas utile ici car tu a initialiser la valeur de statusCode a 400

2023-10-15 13:40 UTC, CDjepeno approved these changes

2023-10-15 13:41 UTC, merged