On 3 creer un livre nest
CDjepeno/OnlineBookApi pull request #37
Opened 2024-03-07 09:17 UTC by hassanrobleh

2024-03-07 10:16 UTC, CDjepeno requested changes
Le fichier node.module ne doit pas etre commiter

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/controllers/book/book.controller.ts
> +      console.log(result);
A retirer stp

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/book/AddBook/add.book.response.ts
> +  approved: number;
Elle sert quoi cette propriéter appoved ?

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/user/getuser/get.user.response.ts
> +export type GetUserResponse = {
A modifier en login.user.response

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/user/getuser/get.user.request.ts
> +export interface GetUserRequest {
A modifier en login.user.request

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/user/getuser/login.user.usecase.ts
> +  async execute(request: GetUserRequest): Promise<GetUserResponse> {
Pareil ici a modifier loginUserRequest, loginUserResponse

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/models/book.entity.ts
Renommer le fichier book.model.ts

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/models/user.entity.ts
> +  // books: Book[];
Commentaires a enlever

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/models/user.entity.ts
> +    const saltRounds = 10; // Nombre de rounds pour générer le sel
pareil commentaire a enlever

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/models/user.entity.ts
Modifier le nom du fichier user.model.ts

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/services/user.repository.typeorm.ts
> +  async signIn(siginIn: GetUserRequest): Promise<GetUserResponse> {
Modifier GetUserRequest => LoginUserRequest | GetUserResponse => LoginUserResponse

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/services/user.repository.typeorm.ts
> +    console.log('Mot de passe stocké :', user.password);
Commentaire a enlever

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/services/user.repository.typeorm.ts
> +      );
Commentaire a enlever

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/services/user.repository.typeorm.ts
> +    console.log("Authentification réussie pour l'utilisateur :", user.email);
Commentaire a enlever

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/infras/common/decorators/is-date-format.decorator.ts
> +    return false; // Garantit que la valeur est bien une instance de Date
Commentaire a retirer

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/domaine/repositories/user.repository.ts
> +  signIn(user: GetUserRequest): Promise<GetUserResponse>;
A modifier GetUserRequest => loginUserRequest | GetUserResponse => loginUserResponse

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/user/adduser/add.user.usecase.ts
> +      const user = new User(
c'est pas ici que tu doit faire sa, c'est dans le service de l'infra que tu instancie la classe User qui elle correspond au model de typeorm

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/book/AddBook/add.book.usecase.ts
> +      console.log(book);
A supprimer

2024-03-07 10:16 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/book/AddBook/add.book.usecase.ts
> +      const book = new Book(
Pareil ici tu ne doit pas instancier ton book ici. c'est dans le service que tu doit le faire

2024-03-08 09:01 UTC, hassanrobleh commented on src/infra/nest/src/application/usecases/book/AddBook/add.book.response.ts
> +  approved: number;
Approved permet de checker le droit d'auteur.

2024-03-08 09:24 UTC, CDjepeno commented on src/infra/nest/src/application/usecases/book/AddBook/add.book.response.ts
> +  approved: number;
Du coup sa va être checker par le back ?
Donc c'est une nouvelle fonctionnalité que tu veux mettre en place ?
Tu va implémenter cette fonctionnalité après ce ticket ?

2024-03-12 22:41 UTC, hassanrobleh commented on src/infra/nest/src/infras/controllers/book/book.controller.ts
> +      console.log(result);
ok

2024-03-12 22:45 UTC, hassanrobleh commented on src/infra/nest/src/application/usecases/book/AddBook/add.book.response.ts
> +  approved: number;
C'est mieux qu'on avance sur les autres tickets

2024-03-12 23:16 UTC, hassanrobleh commented on src/infra/nest/src/application/usecases/user/adduser/add.user.usecase.ts
> +      const user = new User(
Cette classe User représente l'entité dans le domaine et sa va nous facilite de tester la logique métier

2024-03-12 23:18 UTC, hassanrobleh commented on src/infra/nest/src/domaine/repositories/user.repository.ts
> +  signIn(user: GetUserRequest): Promise<GetUserResponse>;
ok

2024-03-14 21:17 UTC, CDjepeno approved these changes

2024-03-14 21:17 UTC, merged